version: "3.8"
services:
  node:
    build:
      context: ./node
      dockerfile: ./Dockerfile
    ports:
      - "9001:9001"
  master:
    build:
      context: ./master
      dockerfile: ./Dockerfile
    ports:
      - "9002:9002"
