version: "3.8"
services:
  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    ports:
      - "9005:9005"
    networks:
      - sharded-storage

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    ports:
      - "9001:9001"
      - "9003:9003"
      - "9004:9004"
    environment:
      - DISCOVERY_GRPC_HOST=discovery
      - SERVICE_ID=1
      - SERVICE_TYPE=NODE
      - SERVICE_HOST=localhost
      - SERVICE_CONTAINER_NAME=node-1
    networks:
      - sharded-storage
    depends_on:
      - master
      - discovery

  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    ports:
      - "9002:9002"
    environment:
      - DISCOVERY_GRPC_HOST=discovery
      - SERVICE_TYPE=MASTER
      - SERVICE_HOST=localhost
      - SERVICE_CONTAINER_NAME=master
    networks:
      - sharded-storage
    depends_on:
      - discovery

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DISCOVERY_GRPC_HOST=discovery
      - SERVICE_TYPE=CLIENT
      - SERVICE_HOST=localhost
    networks:
      - sharded-storage
    profiles:
      - client
    depends_on:
      - master
      - node
      - discovery

networks:
  sharded-storage:
    driver: bridge
