version: "3.8"
services:
  node:
    build:
      context: ./node
      dockerfile: ./dev.Dockerfile
    ports:
      - "9001:9001"
      - "9003:9003"
    networks:
      - sharded-storage
  master:
    build:
      context: ./master
      dockerfile: ./dev.Dockerfile
    ports:
      - "9002:9002"
    networks:
      - sharded-storage

networks:
  sharded-storage:
    driver: bridge
