services:
  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    ports:
      - "9003:9003"
    networks:
      - sharded-storage

  #TODO Use Docker Compose Bake, to reuse built targets instead of building each time.

  #node:
  #  build:
  #    context: .
  #    dockerfile: node/Dockerfile
  #  ports:
  #    - "9001:9001"
  #  environment:
  #    - DISCOVERY_GRPC_HOST=discovery
  #    - SERVICE_ID=1
  #    - SERVICE_TYPE=NODE
  #    - SERVICE_HOST=localhost
  #    - SERVICE_CONTAINER_NAME=node-containter-1
  #  networks:
  #    - sharded-storage
  #  depends_on:
  #    - master
  #    - discovery

  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    ports:
      - "9002:9002"
    environment:
      - DISCOVERY_GRPC_HOST=discovery
      - SERVICE_TYPE=MASTER
      - SERVICE_HOST=localhost
      - SERVICE_CONTAINER_NAME=master
    networks:
      - sharded-storage
    depends_on:
      - discovery

  ##client:
  ##  build:
  ##    context: .
  ##    dockerfile: client/Dockerfile
  ##  environment:
  ##    - DISCOVERY_GRPC_HOST=discovery
  ##    - SERVICE_TYPE=CLIENT
  ##    - SERVICE_HOST=localhost
  ##  networks:
  ##    - sharded-storage
  ##  profiles:
  ##    - client
  ##  depends_on:
  ##    - master
  ##    - node
  ##    - discovery

networks:
  sharded-storage:
    name: sharded-storage
    driver: bridge
