name: sharded-storage-CI-CD-workflow
run-name: ${{ github.actor }} is running CI pipeline
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Build Job is triggered by ${{ github.event_name }} event."
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Grant permissions to gradlew
        run: chmod +x gradlew
      - name: Build and test projects
        run: ./gradlew :node:test :client:test :master:test :discovery:test
      - name: Generate Jacoco reports
        if: always()
        run: ./gradlew :node:jacocoTestReport :client:jacocoTestReport :master:jacocoTestReport :discovery:jacocoTestReport
      - name: Generate Allure reports
        if: always()
        run: ./gradlew :node:allureReport :client:allureReport :master:allureReport :discovery:allureReport
      - name: Store reports as job artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            **/node/build/reports/
            **/client/build/reports/
            **/master/build/reports/
            **/discovery/build/reports/
      - name: Deploy test reports to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: |
            **/build/reports/allure-report/allureReport
      - run: echo "This job's status is ${{ job.status }}"
